# Generated by Django 3.0.3 on 2020-02-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_id', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('domain', models.TextField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Both', 'Both')], max_length=100)),
                ('about_us', models.TextField(max_length=1000)),
                ('image1', models.ImageField(upload_to='slider/')),
                ('image2', models.ImageField(null=True, upload_to='slider/')),
                ('image3', models.ImageField(null=True, upload_to='slider/')),
                ('image4', models.ImageField(null=True, upload_to='slider/')),
                ('image5', models.ImageField(null=True, upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField(choices=[('Computer_Science', 'Computer_Science'), ('Information_Technology', 'Information_Technology'), ('Electronics_Engineering', 'Electronics_Engineering'), ('Electrical_Engineering', 'Electrical_Engineering'), ('Instrumentation_Engineering', 'Instrumentation_Engineering'), ('Mechanical_Engineering', 'Mechanical_Engineering'), ('Civil_Engineering', 'Civil_Engineering'), ('MBA', 'MBA'), ('Chemical', 'Chemical')], max_length=100)),
                ('hod', models.TextField(max_length=100)),
                ('count', models.CharField(max_length=50)),
                ('vision_mission', models.TextField(max_length=1000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField(null=True)),
                ('forum_type', models.TextField(choices=[('Announcement', 'Announcement'), ('CollegeLevel', 'CollegeLevel'), ('DepartmentLevel', 'DepartmentLevel'), ('SemesterLevel', 'SemesterLevel')], max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField(max_length=500)),
                ('event_image', models.ImageField(null=True, upload_to='events/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusStatusTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('unit_name', models.CharField(max_length=10)),
                ('topics', models.TextField(max_length=1000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='taught_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Teacher'),
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=500)),
                ('sent_at', models.DateTimeField(null=True)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Forum')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
    ]
