# Generated by Django 3.0 on 2020-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='domain',
            field=models.TextField(choices=[('DepartmentType', 'DepartmentType'), ('Engineering Management All', 'Engineering Management All')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
