# Generated by Django 3.0 on 2020-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.TextField(choices=[('Computer_Science', 'Computer_Science'), ('Information_Technology', 'Information_Technology'), ('Electronics_And_Communication_Engineering', 'Electronics_And_Communication_Engineering'), ('Electrical_Engineering', 'Electrical_Engineering'), ('Instrumentation_Engineering', 'Instrumentation_Engineering'), ('Mechanical_Engineering', 'Mechanical_Engineering'), ('Civil_Engineering', 'Civil_Engineering'), ('Master_of_Business_Administration', 'Master_of_Business_Administration'), ('Chemical', 'Chemical')], max_length=100),
        ),
    ]
