# Generated by Django 3.0.3 on 2020-02-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField(max_length=500)),
                ('event_image', models.ImageField(null=True, upload_to='events/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
            ],
        ),
    ]
