# Generated by Django 3.0.3 on 2020-02-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_upcomingevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummessage',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
