# Generated by Django 3.0 on 2020-02-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200223_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='user_id',
            new_name='applicant_id',
        ),
    ]
