# Generated by Django 3.0.3 on 2020-02-23 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_college_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='domain',
        ),
        migrations.AddField(
            model_name='college',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
