# Generated by Django 3.0 on 2020-02-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200224_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.TextField(choices=[('Computer_Science', 'Computer_Science'), ('Information_Technology', 'Information_Technology'), ('Electronics_Engineering', 'Electronics_Engineering'), ('Electrical_Engineering', 'Electrical_Engineering'), ('Instrumentation_Engineering', 'Instrumentation_Engineering'), ('Mechanical_Engineering', 'Mechanical_Engineering'), ('Civil_Engineering', 'Civil_Engineering'), ('MBA', 'MBA'), ('Chemical', 'Chemical')], max_length=100),
        ),
    ]
