# Generated by Django 3.0.3 on 2020-02-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200223_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
